### ISSUE TITLE
there is new compiling issue with this setup..

### ISSUE THREAD

**Issue by jjhesk** [a-student/BetterVectorDrawable#12]
apply plugin: 'com.android.library'
repositories {
    maven { url "http://dl.bintray.com/jjhesk/maven" }
    maven { url 'http://dl.bintray.com/madcyph3r/maven/' }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}
android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'

```
defaultConfig {
    minSdkVersion 17
    targetSdkVersion 22
    versionCode 10
    versionName "1.5"
   // generatedDensities = []
}
buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
}
packagingOptions {
    exclude 'META-INF/services/javax.annotation.processing.Processor'
}
```

}

dependencies {
    compile 'com.android.support:support-annotations:23.1.1'
    compile 'com.android.support:support-v13:23.1.1'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:percent:23.1.1'
    compile 'net.soulwolf.widget:ratiolayout:1.0.0'
    compile 'xyz.danoz:recyclerviewfastscroller:0.1.3'
    compile 'com.ogaclejapan.smarttablayout:utils-v13:1.4.2@aar'
    compile 'com.ogaclejapan.smarttablayout:library:1.4.2@aar'
    compile 'com.marshalchen.ultimaterecyclerview:library:0.3.18'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.hkm.advancedtoolbar:advancedtoolbar:0.6.1'
  //  compile 'com.bettervectordrawable:lib:0.7'
//    compile 'com.telly:mrvector:0.2.0'
   //   compile 'com.jakewharton:butterknife:7.0.1'
}

**Comment by 13rac1** [comment]
What is the issue? Error message?

**Comment by a-student** [comment]
jjhesk, could you please provide more info?

**Comment by 13rac1** [comment]
@a-student It's been two weeks since I asked, IMO you can safely close this issue.
