### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by Twinkle942910** [a-student/BetterVectorDrawable#14]
Hi there)
How can i connect animation to SVG in your library? Is it possible? Can I use standart way from here? Because that doesn't work(
http://developer.android.com/intl/ru/training/material/animations.html#AnimVector
I done this way.
Sory for my english) Thanks)

**Comment by a-student** [comment]
Hi!
AnimatedVectorDrawable is not supported by the lib.

**Comment by Twinkle942910** [comment]
Thank you, its a pitty(
But thanks for your work!)

**Comment by a-student** [comment]
Not at all, by the way if you add support for AnimatedVectorDrawable, i would be happy to approve pull request.
