### ISSUE TITLE
Add link to xamarin binding for BetterVectorDrawable.

### ISSUE THREAD

**Issue by vadzim-vys** [a-student/BetterVectorDrawable#17]
Hi,
I've created xamarin binding for BetterVectorDrawable library. Can you please add link to this https://github.com/VysotskiVadim/XamarinBetterVectorDrawable repository in README.md in order to xamarin developers can find xamarin version of BetterVectorDrawable library.

**Comment by a-student** [comment]
Hi,
Thank you very much for your effort!
Please, make a pull request to this repo with corresponding edits in the readme file.
