### ISSUE TITLE
AnimatedVectorDrawable

### ISSUE THREAD

**Issue by juliocbcotta** [a-student/BetterVectorDrawable#3]
Is it possible to use this library to get the drawable to be animated like:
https://developer.android.com/reference/android/graphics/drawable/AnimatedVectorDrawable.html

**Comment by a-student** [comment]
No, AnimatedVectorDrawable is not supported.

**Comment by vyndor** [comment]
Any chance to see it in the future?

**Comment by a-student** [comment]
Personally, I do not have time on this task. But I would be happy to approve pull request ;)
