### ISSUE TITLE
Gradle build issue

### ISSUE THREAD

**Issue by VadimWelldone** [a-student/BetterVectorDrawable#5]
Hi @a-student .

Firstly, thanks for your cool library :+1: 

During its integration to my project I have experienced following issue:

:processDebugResources
Android/res/values/colors.xml
Error:(2) Attribute "strokeWidth" has already been defined
Error:(2) Attribute "strokeColor" has already been defined
Error:(2) Attribute "fillColor" has already been defined
Error:Execution failed for task ':processDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/vadim/Library/Android/sdk/build-tools/23.0.0/aapt'' finished with non-zero exit value 1

Project settings:

compileSdkVersion 23
buildToolsVersion '23.0.0'
targetSdkVersion 23

compile 'com.android.support:appcompat-v7:22.2.1'
compile 'com.android.support:support-v4:23.0.1'

I hope you can shed light on this issues and what should I do.

Thanks in advance.

**Comment by VadimWelldone** [comment]
Also, I have noticed that, probably, this string causes issue:

compile 'com.viewpagerindicator:library:2.4.1'

When I comments that dependency, everything works like a charm.

**Comment by a-student** [comment]
Hi Vadim,
This happens because those attributes are defined simultaneously in both libraries. Just attach the ViewPagerIndicator library as source code (not as gradle dependency) and rename duplicate attributes.

**Comment by VadimWelldone** [comment]
Thanks @a-student . I will try!
