### ISSUE TITLE
invalid drawable tag vector

### ISSUE THREAD

**Issue by Y-E-P** [a-student/BetterVectorDrawable#6]
android.view.InflateException: Binary XML file line #22: Error inflating class android.widget.ImageView
Binary XML file line #2<vector> tag requires viewportHeight > 0
the 22 line contains this:
<ImageView
        android:id="@+id/imageView2"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/mb_logo_vector" />

The App class contains this:
VectorDrawableCompat.enableResourceInterceptionFor(getResources(), R.drawable.mb_logo_vector);

What I do wrong?
P.S. In android 5 and higher it works fine,on android 4.0.4 it not works.

**Comment by a-student** [comment]
Make sure vector drawable has `viewportHeight` attribute set. It should look like

``` xml
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:better="http://schemas.android.com/apk/res-auto"
    android:width="100dp"
    android:height="100dp"
    android:viewportHeight="100"
    android:viewportWidth="100"
    better:viewportHeight="100"
    better:viewportWidth="100">
```

**Comment by Y-E-P** [comment]
Thanks,but I fixed this problem by write last api to buildSDK buildToolsVersion '23.0.2'

**Comment by a-student** [comment]
You probably do not need this lib then. Please, read README.md
